[package]
name = "Wayland_Windowing_Rust"
version = "0.1.0"
edition = "2021"

[dependencies]
wayland-client = "0.31.7"
wayland-scanner = "0.31.5"
wayland-protocols = { version = "0.32.5", features = ["client"] }
tempfile = "3.2"
